<?php

namespace ioext\laravel_db;

use Illuminate\Database\Eloquent\Model;

class CQueryBaseExtension extends Model
{
    public $timestamps = false;

    public static function getTableName()
    {
        return parent::getTable(); // TODO: Change the autogenerated stub
    }

}